config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :create] do
    resources :reviews, only: :create
    resources :doses, only: [:new, :create]

  end


  resources :doses, only: :destroy

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true
  has_one_attached :photo
  has_many :reviews, dependent: :delete_all


  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [ :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :delete_all
  validates :name, uniqueness: true
  validates :name, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  RATING = [1, 2, 3, 4, 5]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index

    if params[:query].present?
      @cocktails = Cocktail.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @cocktails = Cocktail.all
    end
    @cocktail = Cocktail.new

  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @review = Review.new
    @reviews = Review.all
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail)


  end

  private

  def cocktail_params
  params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController


  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail_id)
  end



   def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def create
  @review = Review.new(review_params)

  @cocktail = Cocktail.find(params[:cocktail_id])
  @review.cocktail = @cocktail
  @review.save
  redirect_to cocktail_path(@cocktail)

end


def review_params
    params.require(:review).permit(:content, :rating, :cocktail_id)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=image_path "banner.jpg"%>); background-position: bottom; background-size: cover;">
  <div class="banner-wrapper text-center">
    <%= image_tag('logo-cc2.png', crop: :fill) %>

  </div>
</div>

<div class=" container d-flex justify-content-between mb-4 p-5">

    <div class="btn btn-flat-2" id="myBtn" >Add a Cocktail</div>
    <div style="display: flex">
      <div>
      <%= form_tag cocktails_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-cocktails",
        placeholder: "Find a cocktail"
        %>
        </div>
         <%= submit_tag "Search", class: "btn btn-flat-search " %>
      <% end %>
    </div>
</div>

<div class="container text-center">

  <div class="row d-flex justify-content-center ">

    <% @cocktails.each do |c| %>
      <%= link_to cocktail_path(c) do  %>
        <div class="card-category col-12 " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path c.photo.key%>)">
          <%= c.name %>
        </div>
      <% end %>
    <% end %>

  </div>
  </div>



<div id="myPopup" class="popup">


  <!-- Modal content -->
  <div class="popup-content">
    <div class="popup-border">
      <span class="close">&times;</span>
        <%= simple_form_for(@cocktail) do |f| %>
         <%= f.input :name, label: "Name your cocktail!" %>
         <%= f.input :photo, as: :file %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>


</div>

app/views/cocktails/show.html.erb
<div class="banner-cocktail" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @cocktail.photo.key %>)">
  <div class="h-100 d-flex align-items-center justify-content-center">
    <h1 style="color: #fea5db; font-size: 78px;">
      <%=@cocktail.name %>
    </h1>

  </div>
</div>


  <div class="show-wrapper">
    <div class="border-blue">
      <div class="border-pink">
        <div class="border-blue">
          <div class="border-pink">
            <div class="border-blue row" style="background: black">
              <div class="border-pink show-content col-7  ">
                <h2>Ingredients</h2>
                <% @cocktail.doses.each do |dose|  %>
                  <div>
                    <p>
                      <%= dose.ingredient.name%>, <%= dose.description %>
                      <%= link_to dose_path(dose),
                       method: :delete,
                       remote: true do  %>
                       <i class="fas fa-trash-alt"></i>
                       <% end %>
                    </p>
                    </div>
                <% end %>
                <div class="btn btn-flat-2 ml-0" id="myBtn" >Add an ingredient</div>
                <div class="border mt-4 mb-2"></div>

                  <h2>Reviews</h2>
                  <% if @cocktail.reviews.exists? %>
                    <% @cocktail.reviews.each do |r| %>
                     <div class="d-flex ">
                       <p><em> - <%= r.content %> </em> </p>
                       <p class="ml-4">
                        <% r.rating.to_i.times do %>
                        <i class="fas fa-star"></i>
                        <% end %>
                       </p>
                     </div>
                    <% end %>

                  <% else %>
                    <p><em>No reviews yet, leave a review up to the right if you like it <3 </em></p>
                  <% end %>



              </div>
              <div class="col show-content-review">
                <h2>Leave a review!</h2>
                  <%= simple_form_for([ @cocktail, @review ], remote: true) do |form| %>
                    <%= form.label :rating %>
                    <%= form.select :rating, [1,2,3,4,5] %>
                    <%= form.input :content, label: 'Comment', as: :text %>
                    <%= form.button :submit, label:'Add ingredient', class: "btn btn-flat-2 ml-0" %>
                 <% end %>
             </div>


            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


<div id="myPopup" class="popup">


  <!-- Modal content -->
  <div class="popup-content">
    <div class="popup-border">
      <span class="close">&times;</span>
         <%= simple_form_for([ @cocktail, @dose ]) do |form| %>
          <%= form.association :ingredient %>
          <%= form.input :description %>
          <%= form.button :submit, label:'Add ingredient', class: "btn btn-flat" %>

      <% end %>
    </div>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoolCocktails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>